apiVersion: v1
kind: Pod
metadata:
  name: episode-04
  labels:
    app: episode-04
spec:
  nodeSelector:
    kubernetes.io/hostname: scd-assignment03-cluster-m03
  containers:
  - name: episode04-backend-container
    image: mabdullah12/episode04-backend:latest
    ports:
    - containerPort: 3007
    env:
    - name: MONGO_URL
      value: "mongodb://localhost:27017/mydb"
    - name: REACT_APP_BACKEND_URL
      value: "http://localhost:3004"
  - name: frontend-container
    image: mabdullah12/episode04-frontend:latest
    ports:
    - containerPort: 8083
    env:
    - name: REACT_APP_BACKEND_URL
      value: "http://localhost:3004"
  - name: mongodb-container
    image: mongo:latest
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: episode04-mongo-data
      mountPath: /data/db
  volumes:
  - name: episode04-mongo-data
    persistentVolumeClaim:
      claimName: mongo-pvc