apiVersion: v1
kind: Pod
metadata:
  name: episode-05
  labels:
    app: episode-05
spec:
  nodeSelector:
    kubernetes.io/hostname: scd-assignment03-cluster-m03
  initContainers:
  - name: init-mongo
    image: busybox
    command: ['sh', '-c', 'rm -f /data/db/mongod.lock']
    volumeMounts:
    - name: episode05-mongo-data
      mountPath: /data/db
  containers:
  - name: episode05-backend-container
    image: mabdullah12/episode05-backend:latest
    ports:
    - containerPort: 3008
    env:
    - name: MONGO_URL
      value: "mongodb://localhost:27018/mydb"
    - name: REACT_APP_BACKEND_URL
      value: "http://localhost:3004"
  - name: frontend-container
    image: mabdullah12/episode05-frontend:latest
    ports:
    - containerPort: 8084
    env:
    - name: REACT_APP_BACKEND_URL
      value: "http://localhost:3004"
  - name: mongodb-container
    image: mongo
    ports:
    - containerPort: 27018
    volumeMounts:
    - name: episode05-mongo-data
      mountPath: /data/db
  volumes:
  - name: episode05-mongo-data
    persistentVolumeClaim:
      claimName: mongo-pvc-episode-05
