apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-episode-05
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/episode-05